language: go
sudo: required

go:
- "1.11.x"

env:
- GO111MODULE=on

arch:
  packages:
    - go
  script:
    - make test

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
