language: go
sudo: required

arch:
  packages:
    - go
  script:
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure --vendor-only -v
    - make test

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
